vim.api.nvim_set_keymap('n', '<TAB>', ':bn!<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<S-TAB>', ':bN!<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<A-x>', ':BufferClose!<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-s>', ':BufferPick!<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<A->', ':BufferMoveNext!<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<A-<>', ':BufferMovePrevious!<CR>', { noremap = true, silent = true })
