general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear
    before_sleep_cmd = loginctl lock-session    # bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # encender pantalla al despertar
}

listener {
    timeout = 300                                # 5 minutos
    on-timeout = loginctl lock-session           # bloquea la sesión
}

listener {
    timeout = 600                                # 10 minutos
    on-timeout = hyprctl dispatch dpms off       # apaga el monitor
    on-resume = hyprctl dispatch dpms on         # lo enciende al volver
}

