$mod = SUPER
$myTerm = kitty

xwayland {
  force_zero_scaling = true
  enabled = false
}
########################
# MONITOR (auto detect)
########################
monitor=,preferred,auto,1

########################
# INPUT
########################
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
}

########################
# GENERAL
########################
general {
    border_size = 2
    gaps_in = 6
    gaps_out = 12
    layout = dwindle
}

############################
# DECORATION (GLASS)
############################
decoration {
    rounding = 14

    active_opacity = 0.95
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 6
        passes = 2
        noise = 0.02
        contrast = 1.1
        brightness = 0.9
        new_optimizations = true
    }

    # drop_shadow = true
    # shadow_range = 18
    # shadow_render_power = 3
    # col.shadow = rgba(00000055)
}
bind = $mod, M, exec, ~/.config/scripts/move_screen.sh

############################
# ANIMATIONS (SUAVES)
############################
animations {
    enabled = true

    bezier = smooth, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 4, smooth
    animation = windowsOut, 1, 3, smooth, popin 80%
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, smooth, slide
}

############################
# DWINDLE
############################
dwindle {
    pseudotile = true
    preserve_split = true
}


########################
# KEYBINDS (tu layout intacto)
########################

bind = $mod, Q, killactive,
bind = $mod, RETURN, exec, $myTerm

# Launcher
bind = $mod, SPACE, exec, wofi --show drun
bind = $mod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

# Focus HJKL
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r


# Fullscreen
bind = $mod, G, fullscreen,

# Floating
bind = $mod SHIFT, SPACE, togglefloating
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
bindm = $mod, BTN_MIDDLE, centerwindow

# Move window
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

# Move to workspace
bind = $mod SHIFT, A, movetoworkspace, 1
bind = $mod SHIFT, S, movetoworkspace, 2
bind = $mod SHIFT, D, movetoworkspace, 3
bind = $mod SHIFT, F, movetoworkspace, 4
bind = $mod SHIFT, U, movetoworkspace, 5
bind = $mod SHIFT, I, movetoworkspace, 6
bind = $mod SHIFT, O, movetoworkspace, 7
bind = $mod SHIFT, P, movetoworkspace, 8

bind = $mod, A, workspace, 1
bind = $mod, S, workspace, 2
bind = $mod, D, workspace, 3
bind = $mod, F, workspace, 4
bind = $mod, U, workspace, 5
bind = $mod, I, workspace, 6
bind = $mod, O, workspace, 7
bind = $mod, P, workspace, 8

# Para mover al monitor de la derecha/izquierdjj
#bind = $mod ALT, J, movewindow, mon:r
#bind = $mod ALT, H, movewindow, mon:l
#bind = $mod ALT, K, movewindow, mon:u
#bind = $mod ALT, L, movewindow, mon:d
########################
# AUDIO
########################
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioMute, exec, ~/.config/scripts/mute-scripts.sh

########################
# BRILLO
########################
bind = , XF86MonBrightnessUp, exec, light -A 5
bind = , XF86MonBrightnessDown, exec, light -U 5

########################
# WINDOW RULES
########################
# windowrulev2 = workspace 1,class:^(Thunderbird)$
# windowrulev2 = workspace 2,class:^(Firefox)$
# windowrulev2 = workspace 3,class:^(Pcmanfm)$
#
# windowrulev2 = float,class:^(Galculator)$
# windowrulev2 = float,class:^(Pavucontrol)$
# windowrulev2 = float,class:^(GParted)$
# windowrulev2 = fullscreen,class:^(Oblogout)$

########################
# AUTOSTART
########################
exec-once = waybar
exec-once = dunst
exec-once = nm-applet
exec-once = bash ~/.config/scripts/autostart.sh


